---

- name: Add apt key for InfluxDB
  apt_key: url=https://repos.influxdata.com/influxdb.key

- name: Add InfluxDB repository
  apt_repository: repo="deb https://repos.influxdata.com/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable"

- name: Install Influxdb
  apt: name=influxdb state=latest update_cache=yes
 # notify: start influxdb

- name: Configure Influxdb
  template: 
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
#  notify: start influxdb
  

- name: start influxdb
  service: name=influxdb state=started enabled=yes