---
 - name: install zookeeper by specific OS
   include: Debian.yml
   when: ansible_os_family=="Debian"

 - name: ensure zookeeper port is reachable by client
   wait_for: state=started port={{ zookeeper_client_port }} timeout=30
