---

- name: Add Grafana repository
  apt_repository: repo="deb https://packagecloud.io/grafana/stable/debian/ jessie main"

- name: Add Package Cloud key
  apt_key: url=https://packagecloud.io/gpg.key

- name: Install dependencies
  apt: name=grafana state=latest update_cache=yes
  notify: start grafana